version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    # On utilise mambaforge pour gérer les dépendances complexes (GIS)
    python: "mambaforge-22.9"

# On pointe vers ton nouveau fichier de configuration Conda
conda:
  environment: environment.yml

sphinx:
   configuration: docs/conf.py
   fail_on_warning: false
