name: gis-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinx
  - pyrosm
  - geopandas
  - fiona   
  - shapely  
  - pyproj     
  - cartopy
  - matplotlib
  - pandas
  - pip
  - earthengine-api
  - pip:
      - geemap
      - myst-nb
      - nbsphinx
      - sphinx-rtd-theme
      - sphinx-book-theme
